//! Scope rules: parity with slopdetect's `paths.py` and `exclusions.py` on
//! a fixture generated by the Python reference, git attribute resolution,
//! and qlty workspace mode.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use qlty_slop_one::scope::{
    match_generated_header, match_source_path, match_test_path, Category, ExclusionKind,
    ExclusionPolicy, PathScope, QltyWorkspaceScope, Rule, Scope, ScopedPath,
};
use serde_json::{json, Value};
use tempfile::TempDir;

fn path_rules() -> Value {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/scope/path_rules.json");
    serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
}

fn rule_json(rule: Option<Rule>) -> Value {
    match rule {
        Some(rule) => {
            let mut value = serde_json::Map::new();
            if let Some(category) = rule.category() {
                value.insert("category".into(), serde_json::to_value(category).unwrap());
            }
            value.insert("kind".into(), serde_json::to_value(rule.kind()).unwrap());
            value.insert("matched".into(), Value::String(rule.matched().to_owned()));
            Value::Object(value)
        }
        None => Value::Null,
    }
}

fn assert_rule_parity(section: &str, key: &str, rule_for: impl Fn(&str) -> Option<Rule>) {
    let fixture = path_rules();
    let cases = fixture[section].as_array().unwrap();
    let mismatches: Vec<String> = cases
        .iter()
        .filter_map(|case| {
            let input = case[key].as_str().unwrap();
            let actual = rule_json(rule_for(input));
            (actual != case["rule"])
                .then(|| format!("{input:?}: expected {} got {actual}", case["rule"]))
        })
        .collect();
    assert_eq!(mismatches, Vec::<String>::new());
    assert!(!cases.is_empty());
}

#[test]
fn test_path_rules_match_the_reference() {
    assert_rule_parity("test_paths", "path", |path| {
        match_test_path(Path::new(path))
    });
}

#[test]
fn source_path_rules_match_the_reference() {
    assert_rule_parity("source_paths", "path", |path| {
        match_source_path(Path::new(path))
    });
}

#[test]
fn generated_header_rules_match_the_reference() {
    assert_rule_parity("headers", "text", match_generated_header);
}

fn git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .status()
        .unwrap();
    assert!(status.success());
}

fn repository_with_attributes() -> TempDir {
    let temp = tempfile::tempdir().unwrap();
    git(temp.path(), &["init", "-q"]);
    fs::write(
        temp.path().join(".gitattributes"),
        "embedded/** linguist-generated=true\nexternal/** linguist-vendored\n",
    )
    .unwrap();
    fs::create_dir_all(temp.path().join("embedded")).unwrap();
    fs::create_dir_all(temp.path().join("external")).unwrap();
    fs::write(
        temp.path().join("embedded/.gitattributes"),
        "helper.js -linguist-generated\n",
    )
    .unwrap();
    fs::write(temp.path().join("embedded/main.js"), "x\n").unwrap();
    fs::write(temp.path().join("embedded/helper.js"), "x\n").unwrap();
    fs::write(temp.path().join("external/lib.py"), "x\n").unwrap();
    temp
}

#[test]
fn git_attribute_marks_generated_files() {
    let repo = repository_with_attributes();
    let scoped = ScopedPath::resolve(&repo.path().join("embedded/main.js")).unwrap();
    let exclusion = scoped.source_exclusion(None).unwrap().unwrap();
    assert_eq!(exclusion.kind(), ExclusionKind::GitAttribute);
    assert_eq!(exclusion.category(), Some(Category::Generated));
    assert_eq!(exclusion.matched(), "linguist-generated");
}

#[test]
fn nested_git_attributes_override_the_root() {
    let repo = repository_with_attributes();
    let scoped = ScopedPath::resolve(&repo.path().join("embedded/helper.js")).unwrap();
    assert_eq!(scoped.source_exclusion(None).unwrap(), None);
}

#[test]
fn vendored_git_attribute_marks_dependencies() {
    let repo = repository_with_attributes();
    let scoped = ScopedPath::resolve(&repo.path().join("external/lib.py")).unwrap();
    let exclusion = scoped.source_exclusion(None).unwrap().unwrap();
    assert_eq!(exclusion.category(), Some(Category::Dependency));
    assert_eq!(exclusion.matched(), "linguist-vendored");
}

#[test]
fn working_tree_attributes_take_precedence_over_the_index() {
    let repo = repository_with_attributes();
    git(
        repo.path(),
        &["add", ".gitattributes", "embedded/.gitattributes"],
    );
    fs::write(
        repo.path().join(".gitattributes"),
        "embedded/** -linguist-generated\n",
    )
    .unwrap();
    let scoped = ScopedPath::resolve(&repo.path().join("embedded/main.js")).unwrap();
    assert_eq!(scoped.source_exclusion(None).unwrap(), None);
}

#[test]
fn info_attributes_apply_inside_the_repository() {
    let repo = repository_with_attributes();
    fs::create_dir_all(repo.path().join(".git/info")).unwrap();
    fs::write(
        repo.path().join(".git/info/attributes"),
        "embedded/** -linguist-generated\n",
    )
    .unwrap();
    let scoped = ScopedPath::resolve(&repo.path().join("embedded/main.js")).unwrap();
    assert_eq!(scoped.source_exclusion(None).unwrap(), None);
}

#[test]
fn external_repository_name_does_not_exclude_source() {
    let temp = tempfile::tempdir().unwrap();
    let project = temp.path().join("dist/vendor");
    fs::create_dir_all(project.join("src")).unwrap();
    git(&project, &["init", "-q"]);
    let source = project.join("src/lib.rs");
    fs::write(&source, "fn main() {}").unwrap();
    let scoped = ScopedPath::resolve(&source).unwrap();
    assert_eq!(scoped.scope(), PathScope::GitRoot);
    assert_eq!(scoped.source_exclusion(Some("fn main() {}")).unwrap(), None);
}

#[test]
fn repository_scope_ignores_external_test_directories() {
    let temp = tempfile::tempdir().unwrap();
    let project = temp.path().join("tests/ExampleTests");
    fs::create_dir_all(project.join("src")).unwrap();
    fs::create_dir_all(project.join("tests")).unwrap();
    fs::create_dir_all(project.join(".git")).unwrap();
    let production = project.join("src/lib.rs");
    let test = project.join("tests/helper.rs");
    let scoped = ScopedPath::resolve(&production).unwrap();
    assert_eq!(scoped.test_exclusion(), None);
    let exclusion = ScopedPath::resolve(&test)
        .unwrap()
        .test_exclusion()
        .unwrap();
    assert_eq!(exclusion.matched_path(), "tests/helper.rs");
    assert_eq!(exclusion.path_scope(), PathScope::GitRoot);
}

#[test]
fn dot_segments_are_normalized_before_scoping() {
    let temp = tempfile::tempdir().unwrap();
    let project = temp.path().join("tests/ExampleTests");
    fs::create_dir_all(project.join("src")).unwrap();
    fs::create_dir_all(project.join("tests")).unwrap();
    fs::write(project.join(".git"), "gitdir: /some/worktree\n").unwrap();
    let scoped = ScopedPath::resolve(&project.join("tests/../src/lib.rs")).unwrap();
    assert_eq!(scoped.relative(), Path::new("src/lib.rs"));
    assert_eq!(scoped.test_exclusion(), None);
}

#[test]
fn project_manifest_marks_the_project_root() {
    let temp = tempfile::tempdir().unwrap();
    let project = temp.path().join("tests/ExampleTests");
    fs::create_dir_all(project.join("tests")).unwrap();
    fs::write(project.join("Cargo.toml"), "[package]\n").unwrap();
    let exclusion = ScopedPath::resolve(&project.join("tests/helper.rs"))
        .unwrap()
        .test_exclusion()
        .unwrap();
    assert_eq!(exclusion.path_scope(), PathScope::ProjectRoot);
    assert_eq!(exclusion.matched(), "tests");
}

#[test]
fn output_directory_is_excluded_at_the_project_root() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("pyproject.toml"), "").unwrap();
    let exclusion = ScopedPath::resolve(&temp.path().join("dist/output.py"))
        .unwrap()
        .source_exclusion(None)
        .unwrap()
        .unwrap();
    assert_eq!(exclusion.category(), Some(Category::Generated));
    assert_eq!(exclusion.kind(), ExclusionKind::Directory);
}

#[test]
fn generated_header_is_checked_only_with_text() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("pyproject.toml"), "").unwrap();
    let scoped = ScopedPath::resolve(&temp.path().join("api.py")).unwrap();
    assert_eq!(scoped.source_exclusion(None).unwrap(), None);
    let exclusion = scoped
        .source_exclusion(Some("# Generated by tool. DO NOT EDIT.\nvalue = 1\n"))
        .unwrap()
        .unwrap();
    assert_eq!(exclusion.kind(), ExclusionKind::Header);
}

#[test]
fn test_exclusion_serializes_in_reference_key_order() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("Cargo.toml"), "").unwrap();
    let exclusion = ScopedPath::resolve(&temp.path().join("src/lib_test.rs"))
        .unwrap()
        .test_exclusion()
        .unwrap();
    assert_eq!(
        serde_json::to_string(&exclusion).unwrap(),
        r#"{"policy":"test-paths-001","matched_path":"src/lib_test.rs","path_scope":"project-root","kind":"filename","matched":"test"}"#
    );
}

#[test]
fn source_exclusion_serializes_in_reference_key_order() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("Cargo.toml"), "").unwrap();
    let exclusion = ScopedPath::resolve(&temp.path().join("vendor/lib.rs"))
        .unwrap()
        .source_exclusion(None)
        .unwrap()
        .unwrap();
    assert_eq!(
        serde_json::to_string(&exclusion).unwrap(),
        r#"{"matched_path":"vendor/lib.rs","path_scope":"project-root","policy":"authored-source-002","category":"dependency","kind":"directory","matched":"vendor"}"#
    );
}

fn qlty_workspace(config: &str) -> TempDir {
    let temp = tempfile::tempdir().unwrap();
    fs::create_dir_all(temp.path().join(".qlty")).unwrap();
    fs::write(temp.path().join(".qlty/qlty.toml"), config).unwrap();
    git(temp.path(), &["init", "-q"]);
    temp
}

const WORKSPACE_CONFIG: &str = r#"
config_version = "0"
test_patterns = ["**/test/**", "**/*_spec.rb"]
exclude_patterns = ["vendor/**", "!vendor/keep/**", "*.min.js"]

[[plugin]]
name = "rubocop"
"#;

#[test]
fn workspace_test_patterns_replace_the_default_rules() {
    let workspace = qlty_workspace(WORKSPACE_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("lib/test/helper.rb")).unwrap();
    let exclusion = scope.test_exclusion().unwrap();
    assert_eq!(
        exclusion.policy(),
        ExclusionPolicy::QltyWorkspaceTestPatterns
    );
    assert_eq!(exclusion.path_scope(), PathScope::QltyWorkspace);
    assert_eq!(exclusion.kind(), ExclusionKind::Glob);
    assert_eq!(exclusion.matched(), "**/test/**");
    assert_eq!(exclusion.matched_path(), "lib/test/helper.rb");
}

#[test]
fn workspace_mode_ignores_default_test_path_rules() {
    let workspace = qlty_workspace(WORKSPACE_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("tests/helper.rb")).unwrap();
    assert_eq!(scope.test_exclusion(), None);
}

#[test]
fn workspace_exclude_patterns_replace_the_default_rules() {
    let workspace = qlty_workspace(WORKSPACE_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("vendor/lib.rb")).unwrap();
    let exclusion = scope.source_exclusion(None).unwrap().unwrap();
    assert_eq!(
        exclusion.policy(),
        ExclusionPolicy::QltyWorkspaceExcludePatterns
    );
    assert_eq!(exclusion.category(), Some(Category::Configured));
    assert_eq!(exclusion.matched(), "vendor/**");
    assert_eq!(
        serde_json::to_value(&exclusion).unwrap(),
        json!({
            "matched_path": "vendor/lib.rb",
            "path_scope": "qlty-workspace",
            "policy": "qlty-workspace-exclude-patterns",
            "category": "configured",
            "kind": "glob",
            "matched": "vendor/**"
        })
    );
}

#[test]
fn workspace_negated_patterns_keep_files_in_scope() {
    let workspace = qlty_workspace(WORKSPACE_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("vendor/keep/lib.rb")).unwrap();
    assert_eq!(scope.source_exclusion(None).unwrap(), None);
}

#[test]
fn workspace_mode_ignores_default_source_rules_and_headers() {
    let workspace = qlty_workspace(WORKSPACE_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("node_modules/pkg/index.js")).unwrap();
    assert_eq!(
        scope.source_exclusion(Some("// @generated\n")).unwrap(),
        None
    );
}

#[test]
fn workspace_without_patterns_keeps_the_default_rules() {
    let workspace = qlty_workspace("config_version = \"0\"\n");
    let scope = Scope::try_new(&workspace.path().join("tests/helper.rb")).unwrap();
    let exclusion = scope.test_exclusion().unwrap();
    assert_eq!(exclusion.policy(), ExclusionPolicy::TestPaths);
    assert_eq!(exclusion.path_scope(), PathScope::GitRoot);
    assert_eq!(exclusion.matched(), "tests");
    let scope = Scope::try_new(&workspace.path().join("vendor/lib.rb")).unwrap();
    let exclusion = scope.source_exclusion(None).unwrap().unwrap();
    assert_eq!(exclusion.policy(), ExclusionPolicy::AuthoredSource);
    assert_eq!(exclusion.matched(), "vendor");
}

const EXTENDING_CONFIG: &str = r#"
config_version = "0"
test_patterns = ["...", "**/*_spec.rb"]
exclude_patterns = ["...", "legacy/**"]
"#;

#[test]
fn extended_test_patterns_are_checked_before_the_default_rules() {
    let workspace = qlty_workspace(EXTENDING_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("tests/thing_spec.rb")).unwrap();
    let exclusion = scope.test_exclusion().unwrap();
    assert_eq!(
        exclusion.policy(),
        ExclusionPolicy::QltyWorkspaceTestPatterns
    );
    assert_eq!(exclusion.path_scope(), PathScope::QltyWorkspace);
    assert_eq!(exclusion.matched(), "**/*_spec.rb");
}

#[test]
fn extended_test_patterns_fall_back_to_the_default_rules() {
    let workspace = qlty_workspace(EXTENDING_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("tests/helper.rb")).unwrap();
    let exclusion = scope.test_exclusion().unwrap();
    assert_eq!(exclusion.policy(), ExclusionPolicy::TestPaths);
    assert_eq!(exclusion.path_scope(), PathScope::GitRoot);
    assert_eq!(exclusion.kind(), ExclusionKind::Directory);
}

#[test]
fn extended_exclude_patterns_are_checked_before_the_default_rules() {
    let workspace = qlty_workspace(EXTENDING_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("legacy/vendor/lib.rb")).unwrap();
    let exclusion = scope.source_exclusion(None).unwrap().unwrap();
    assert_eq!(
        exclusion.policy(),
        ExclusionPolicy::QltyWorkspaceExcludePatterns
    );
    assert_eq!(exclusion.matched(), "legacy/**");
}

#[test]
fn extended_exclude_patterns_fall_back_to_the_default_rules_and_headers() {
    let workspace = qlty_workspace(EXTENDING_CONFIG);
    let scope = Scope::try_new(&workspace.path().join("vendor/lib.rb")).unwrap();
    let exclusion = scope.source_exclusion(None).unwrap().unwrap();
    assert_eq!(exclusion.policy(), ExclusionPolicy::AuthoredSource);
    assert_eq!(exclusion.category(), Some(Category::Dependency));
    let scope = Scope::try_new(&workspace.path().join("lib/client.rb")).unwrap();
    let exclusion = scope
        .source_exclusion(Some("# @generated\n"))
        .unwrap()
        .unwrap();
    assert_eq!(exclusion.kind(), ExclusionKind::Header);
}

#[test]
fn an_extender_alone_keeps_the_default_rules() {
    let workspace = qlty_workspace("test_patterns = [\"...\"]\nexclude_patterns = [\"...\"]\n");
    let scope = Scope::try_new(&workspace.path().join("tests/helper.rb")).unwrap();
    assert_eq!(
        scope.test_exclusion().unwrap().policy(),
        ExclusionPolicy::TestPaths
    );
}

#[test]
fn replaced_test_patterns_leave_extended_exclude_patterns_alone() {
    let workspace = qlty_workspace(
        "test_patterns = [\"**/*_spec.rb\"]\nexclude_patterns = [\"...\", \"legacy/**\"]\n",
    );
    let scope = Scope::try_new(&workspace.path().join("tests/helper.rb")).unwrap();
    assert_eq!(scope.test_exclusion(), None);
    let scope = Scope::try_new(&workspace.path().join("vendor/lib.rb")).unwrap();
    assert_eq!(
        scope.source_exclusion(None).unwrap().unwrap().policy(),
        ExclusionPolicy::AuthoredSource
    );
}

#[test]
fn nearest_workspace_wins() {
    let outer = qlty_workspace(WORKSPACE_CONFIG);
    let inner = outer.path().join("nested");
    fs::create_dir_all(inner.join(".qlty")).unwrap();
    fs::write(
        inner.join(".qlty/qlty.toml"),
        "test_patterns = [\"spec/**\"]\n",
    )
    .unwrap();
    let workspace = QltyWorkspaceScope::for_path(&inner.join("lib/test/a.rb"))
        .unwrap()
        .unwrap();
    assert_eq!(workspace.root(), inner);
    assert_eq!(workspace.test_exclusion(), None);
    assert_eq!(
        QltyWorkspaceScope::for_path(&inner.join("spec/a.rb"))
            .unwrap()
            .unwrap()
            .test_exclusion()
            .unwrap()
            .matched(),
        "spec/**"
    );
}

#[test]
fn invalid_workspace_config_is_an_error() {
    let workspace = qlty_workspace("test_patterns = 5\n");
    let error = Scope::try_new(&workspace.path().join("lib/a.rb")).unwrap_err();
    assert!(matches!(
        error,
        qlty_slop_one::Error::WorkspaceConfig { .. }
    ));
}

#[test]
fn files_outside_any_workspace_use_the_default_rules() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("go.mod"), "").unwrap();
    let scope = Scope::try_new(&temp.path().join("pkg/handler_test.go")).unwrap();
    let exclusion = scope.test_exclusion().unwrap();
    assert_eq!(exclusion.policy(), ExclusionPolicy::TestPaths);
    assert_eq!(exclusion.path_scope(), PathScope::ProjectRoot);
}
