//! Byte-exact parity with slopdetect's `prepare_source` on committed Rust
//! fixtures. The `.expected.json` files were generated by the Python
//! reference with tree-sitter-rust 0.24.2.

use std::fs;
use std::path::PathBuf;

use qlty_slop_one::source::PreparedSource;
use serde_json::Value;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/source")
}

fn assert_parity(name: &str) {
    let source = fs::read_to_string(fixture_dir().join(format!("{name}.rs"))).unwrap();
    let expected: Value = serde_json::from_str(
        &fs::read_to_string(fixture_dir().join(format!("{name}.expected.json"))).unwrap(),
    )
    .unwrap();
    let prepared = PreparedSource::prepare(&source, ".rs", false).unwrap();
    assert_eq!(prepared.text(), expected["text"].as_str().unwrap());
    assert_eq!(
        serde_json::to_value(prepared.line_map()).unwrap(),
        expected["line_map"]
    );
    assert_eq!(
        serde_json::to_value(prepared.excluded_modules()).unwrap(),
        expected["excluded_modules"]
    );
    assert_eq!(prepared.has_code(), expected["has_code"].as_bool().unwrap());
    assert_eq!(
        serde_json::to_value(prepared.info()).unwrap(),
        expected["info"]
    );
}

#[test]
fn nested_modules() {
    assert_parity("nested_modules");
}

#[test]
fn macros_and_similar_names() {
    assert_parity("macros_and_similar_names");
}

#[test]
fn same_line() {
    assert_parity("same_line");
}

#[test]
fn multiline_inside_line() {
    assert_parity("multiline_inside_line");
}

#[test]
fn only_tests() {
    assert_parity("only_tests");
}

#[test]
fn raw_names_and_docs() {
    assert_parity("raw_names_and_docs");
}

#[test]
fn modern_syntax_with_tests() {
    assert_parity("modern_syntax_with_tests");
}

#[test]
fn modern_syntax_without_tests() {
    assert_parity("modern_syntax_without_tests");
}
