# Qlty configuration for seller-invoice

[qlty]
analysis_enabled = true
coverage_enabled = true

# Java analysis configuration
[analysis.java]
enabled = true
# Use existing PMD configuration
pmd_config = "config/pmd/pmd.xml"
# Use existing SpotBugs configuration
spotbugs_exclude = "config/spotbugs/spotbugs-exclude.xml"

# Coverage configuration
[coverage]
platform = "jacoco"
# Minimum coverage threshold
minimum_coverage = 80

# File patterns
[files]
include = ["**/*.java"]
exclude = [
    "**/test/**",
    "**/tests/**",
    "**/build/**",
    "**/target/**",
    "**/*Test.java",
    "**/*Tests.java"
]

# Security scanning
[security]
enabled = true
secrets_scanning = true
dependency_scanning = true

# Code quality gates
[gates]
enabled = true
block_on_failure = true