[package]
name = "qlty-slop-one-trends"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
flate2.workspace = true
git2.workspace = true
iana-time-zone.workspace = true
qlty-config.workspace = true
qlty-slop-one.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
