//! Which files are in scope: test files, generated output, dependencies,
//! and documentation are skipped.
//!
//! Inside a qlty workspace (a `.qlty/qlty.toml` ancestor) the workspace's
//! `test_patterns` and `exclude_patterns` decide. Elsewhere slopdetect's
//! rules apply, ported from `paths.py` and `exclusions.py`.

use std::env;
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::sync::OnceLock;

use git2::{AttrCheckFlags, AttrValue, Repository};
use globset::{Glob, GlobSet, GlobSetBuilder};
use qlty_config::config::exclude_group::ExcludeGroup;
use regex::Regex;
use serde::ser::SerializeStruct as _;
use serde::{Deserialize, Serialize, Serializer};

use crate::error::{Error, Result};
use crate::pylines;
use crate::source::is_python_whitespace;

const QLTY_CONFIG_PATH: &str = ".qlty/qlty.toml";

const TEST_WORDS: [&str; 12] = [
    "test",
    "tests",
    "spec",
    "specs",
    "testcase",
    "testcases",
    "testsuite",
    "testsuites",
    "unittest",
    "unittests",
    "browsertest",
    "browsertests",
];
const TEST_DIRECTORY_NAMES: [&str; 25] = [
    "__test__",
    "__tests__",
    "__spec__",
    "__specs__",
    "testing",
    "e2e",
    "cypress",
    "testdata",
    "test_data",
    "test-data",
    "testfixtures",
    "test_fixtures",
    "test-fixtures",
    "fixtures",
    "__fixtures__",
    "__mocks__",
    "__snapshots__",
    "test_support",
    "test-support",
    "test_helpers",
    "test-helpers",
    "integrationtest",
    "integrationtests",
    "functionaltest",
    "functionaltests",
];
const TEST_DIRECTORY_KINDS: [&str; 10] = [
    "integration",
    "functional",
    "acceptance",
    "contract",
    "smoke",
    "system",
    "regression",
    "endtoend",
    "e2e",
    "ui",
];
const JVM_SUFFIXES: [&str; 5] = [".java", ".kt", ".kts", ".scala", ".groovy"];
const PROJECT_MARKERS: [&str; 11] = [
    "pyproject.toml",
    "Cargo.toml",
    "package.json",
    "go.mod",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "Gemfile",
    "composer.json",
    "Package.swift",
    "mix.exs",
];

const OUTPUT_DIRECTORIES: [&str; 20] = [
    "dist",
    "_build",
    "coverage",
    "htmlcov",
    "__pycache__",
    ".next",
    ".nuxt",
    ".output",
    ".svelte-kit",
    ".angular",
    ".parcel-cache",
    ".turbo",
    ".cache",
    ".react-router",
    ".dist-builds",
    ".nyc_output",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".gradle",
];
const DEPENDENCY_DIRECTORIES: [&str; 12] = [
    "node_modules",
    "vendor",
    "third_party",
    "third-party",
    ".venv",
    "venv",
    "site-packages",
    ".yarn",
    ".tox",
    ".git",
    ".hg",
    ".svn",
];
const DOCUMENTATION_DIRECTORIES: [&str; 4] = ["docs", "doc", "documentation", "prototypes"];
/// Ambiguous names that count as output only at a project root or with a
/// recognized compiler-output child, preserving modules such as `src/build`.
const AMBIGUOUS_OUTPUT_DIRECTORIES: [&str; 5] = ["build", "target", "out", "bin", "obj"];
const COMPILER_OUTPUT_CHILDREN: [&str; 5] =
    ["debug", "release", "generated", "classes", "intermediates"];
const GENERATED_SUFFIXES: [&str; 14] = [
    ".min.js",
    ".min.mjs",
    ".min.cjs",
    ".bundle.js",
    ".bundle.mjs",
    ".bundle.cjs",
    ".g.cs",
    ".g.i.cs",
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    "_pb2.py",
    "_pb2_grpc.py",
    ".freezed.dart",
];
/// `.generated.<ext>` and `.gen.<ext>` with any single-segment extension,
/// plus `.g.dart`.
const GENERATED_INFIXES: [&str; 3] = [".generated.", ".gen.", ".g."];
const GENERATED_INFIX_EXTENSIONS: [Option<&str>; 3] = [None, None, Some("dart")];
const GENERATED_COMMENT: &str = r"(?i)^(?:note:\s*)?(?:@generated\b|<auto-generated\b|(?:(?:this\s+is|this)\s+)?(?:file|class|code)\s+(?:(?:is|was|has been)\s+)?(?:auto[- ]?|automatically\s+)?generated\b|(?:automatically\s+|auto[- ]?)generated\b|generated\s+(?:by|with|using)\b|generated from .+\bby\s+antlr\b)";
const HEADER_CHARS: usize = 16384;
const HEADER_LINES: usize = 100;
const HEADER_MATCH_CHARS: usize = 200;
const GIT_ATTRIBUTES: [(&str, Category); 2] = [
    ("linguist-generated", Category::Generated),
    ("linguist-vendored", Category::Dependency),
];

/// The rule set that excluded a file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub enum ExclusionPolicy {
    #[serde(rename = "test-paths-001")]
    TestPaths,
    #[serde(rename = "authored-source-002")]
    AuthoredSource,
    #[serde(rename = "qlty-workspace-test-patterns")]
    QltyWorkspaceTestPatterns,
    #[serde(rename = "qlty-workspace-exclude-patterns")]
    QltyWorkspaceExcludePatterns,
}

impl ExclusionPolicy {
    /// Whether the policy skips test files rather than non-source files.
    pub fn is_test(self) -> bool {
        matches!(self, Self::TestPaths | Self::QltyWorkspaceTestPatterns)
    }
}

/// The root that `matched_path` is relative to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum PathScope {
    GitRoot,
    ProjectRoot,
    WorkingDirectory,
    AbsolutePath,
    QltyWorkspace,
}

/// What kind of evidence matched.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ExclusionKind {
    Directory,
    Filename,
    GitAttribute,
    Header,
    Glob,
}

/// Why a non-test file is out of scope.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Category {
    Generated,
    Dependency,
    Documentation,
    /// Matched by a qlty workspace's `exclude_patterns`.
    Configured,
}

/// A matched exclusion rule before it is tied to a path.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Rule {
    category: Option<Category>,
    kind: ExclusionKind,
    matched: String,
}

impl Rule {
    fn new(category: Option<Category>, kind: ExclusionKind, matched: impl Into<String>) -> Self {
        Self {
            category,
            kind,
            matched: matched.into(),
        }
    }

    pub fn category(&self) -> Option<Category> {
        self.category
    }

    pub fn kind(&self) -> ExclusionKind {
        self.kind
    }

    pub fn matched(&self) -> &str {
        &self.matched
    }
}

/// Why a file was skipped, in slopdetect's JSON shape.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Exclusion {
    policy: ExclusionPolicy,
    matched_path: String,
    path_scope: PathScope,
    rule: Rule,
}

impl Exclusion {
    pub fn policy(&self) -> ExclusionPolicy {
        self.policy
    }

    pub fn matched_path(&self) -> &str {
        &self.matched_path
    }

    pub fn path_scope(&self) -> PathScope {
        self.path_scope
    }

    pub fn category(&self) -> Option<Category> {
        self.rule.category
    }

    pub fn kind(&self) -> ExclusionKind {
        self.rule.kind
    }

    pub fn matched(&self) -> &str {
        &self.rule.matched
    }
}

/// Keys follow the Python dict merge order: test exclusions lead with the
/// policy, source exclusions with the path.
impl Serialize for Exclusion {
    fn serialize<S: Serializer>(&self, serializer: S) -> std::result::Result<S::Ok, S::Error> {
        if self.policy.is_test() {
            let mut state = serializer.serialize_struct("Exclusion", 5)?;
            state.serialize_field("policy", &self.policy)?;
            state.serialize_field("matched_path", &self.matched_path)?;
            state.serialize_field("path_scope", &self.path_scope)?;
            state.serialize_field("kind", &self.rule.kind)?;
            state.serialize_field("matched", &self.rule.matched)?;
            state.end()
        } else {
            let mut state = serializer.serialize_struct("Exclusion", 6)?;
            state.serialize_field("matched_path", &self.matched_path)?;
            state.serialize_field("path_scope", &self.path_scope)?;
            state.serialize_field("policy", &self.policy)?;
            state.serialize_field("category", &self.rule.category)?;
            state.serialize_field("kind", &self.rule.kind)?;
            state.serialize_field("matched", &self.rule.matched)?;
            state.end()
        }
    }
}

/// The scope rules that apply to one file.
#[derive(Debug)]
pub struct Scope {
    mode: ScopeMode,
}

#[derive(Debug)]
enum ScopeMode {
    Workspace(QltyWorkspaceScope),
    Defaults(ScopedPath),
}

impl Scope {
    /// Uses the enclosing qlty workspace's patterns when there is one, and
    /// slopdetect's rules otherwise.
    pub fn try_new(path: &Path) -> Result<Self> {
        let mode = match QltyWorkspaceScope::for_path(path)? {
            Some(workspace) => ScopeMode::Workspace(workspace),
            None => ScopeMode::Defaults(ScopedPath::resolve(path)?),
        };
        Ok(Self { mode })
    }

    pub fn test_exclusion(&self) -> Option<Exclusion> {
        match &self.mode {
            ScopeMode::Workspace(workspace) => workspace.test_exclusion(),
            ScopeMode::Defaults(scoped) => scoped.test_exclusion(),
        }
    }

    /// `text` enables the generated-header rule; pass it once the file has
    /// been read.
    pub fn source_exclusion(&self, text: Option<&str>) -> Result<Option<Exclusion>> {
        match &self.mode {
            ScopeMode::Workspace(workspace) => Ok(workspace.source_exclusion()),
            ScopeMode::Defaults(scoped) => scoped.source_exclusion(text),
        }
    }
}

/// A file located within its repository, project, or working directory so
/// that external ancestors and the repository's own name never match.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ScopedPath {
    root: PathBuf,
    relative: PathBuf,
    scope: PathScope,
}

impl ScopedPath {
    /// Port of `scoped_path`: `.` and `..` are normalized lexically, so a
    /// symlink keeps its user-visible path.
    pub fn resolve(path: &Path) -> Result<Self> {
        let cwd = env::current_dir()?;
        Ok(Self::resolve_from(path, &cwd))
    }

    fn resolve_from(path: &Path, cwd: &Path) -> Self {
        let absolute = absolute_lexical(path, cwd);
        let ancestors = || absolute.ancestors().skip(1);
        let git_root = ancestors().find(|parent| {
            let marker = parent.join(".git");
            marker.is_dir() || marker.is_file()
        });
        if let Some(root) = git_root {
            return Self::within(&absolute, root, PathScope::GitRoot);
        }
        let project_root = ancestors().find(|parent| {
            PROJECT_MARKERS
                .iter()
                .any(|marker| parent.join(marker).is_file())
        });
        if let Some(root) = project_root {
            return Self::within(&absolute, root, PathScope::ProjectRoot);
        }
        if absolute.starts_with(cwd) {
            return Self::within(&absolute, cwd, PathScope::WorkingDirectory);
        }
        Self {
            root: PathBuf::new(),
            relative: absolute,
            scope: PathScope::AbsolutePath,
        }
    }

    fn within(absolute: &Path, root: &Path, scope: PathScope) -> Self {
        let relative = absolute
            .strip_prefix(root)
            .unwrap_or(absolute)
            .to_path_buf();
        Self {
            root: root.to_path_buf(),
            relative,
            scope,
        }
    }

    pub fn relative(&self) -> &Path {
        &self.relative
    }

    pub fn scope(&self) -> PathScope {
        self.scope
    }

    /// Port of `test_file_exclusion`.
    pub fn test_exclusion(&self) -> Option<Exclusion> {
        let rule = match_test_path(&self.relative)?;
        Some(self.exclusion(ExclusionPolicy::TestPaths, rule))
    }

    /// Port of `source_file_exclusion`: path rules, then git attributes
    /// inside a repository, then the generated header when `text` is given.
    pub fn source_exclusion(&self, text: Option<&str>) -> Result<Option<Exclusion>> {
        let mut rule = match_source_path(&self.relative);
        if rule.is_none() && self.scope == PathScope::GitRoot {
            rule = git_attribute_rule(&self.root, &self.relative)?;
        }
        if rule.is_none() {
            rule = text.and_then(match_generated_header);
        }
        Ok(rule.map(|rule| self.exclusion(ExclusionPolicy::AuthoredSource, rule)))
    }

    fn exclusion(&self, policy: ExclusionPolicy, rule: Rule) -> Exclusion {
        Exclusion {
            policy,
            matched_path: self.relative.to_string_lossy().into_owned(),
            path_scope: self.scope,
            rule,
        }
    }
}

/// `os.path.abspath`: join with `cwd` and collapse `.` and `..` lexically.
fn absolute_lexical(path: &Path, cwd: &Path) -> PathBuf {
    let joined = if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    };
    let mut normalized = PathBuf::new();
    for component in joined.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                let is_root = matches!(
                    normalized.components().next_back(),
                    None | Some(Component::RootDir) | Some(Component::Prefix(_))
                );
                if !is_root {
                    normalized.pop();
                }
            }
            other => normalized.push(other),
        }
    }
    normalized
}

fn path_parts(path: &Path) -> Vec<String> {
    path.components()
        .map(|component| match component {
            Component::RootDir => String::from("/"),
            other => other.as_os_str().to_string_lossy().into_owned(),
        })
        .collect()
}

/// Splits a name into lowercase words at separators and camel-case
/// boundaries, keeping `TestClient`, `HTTPTests`, and `androidTest`
/// distinct from `Contest` or `Latest`.
fn words(name: &str) -> Vec<String> {
    let chars: Vec<char> = name.chars().collect();
    let mut separated = String::with_capacity(name.len() + 8);
    for (index, &c) in chars.iter().enumerate() {
        separated.push(c);
        let next = chars.get(index + 1).copied();
        let after_next = chars.get(index + 2).copied();
        let upper_run_boundary = c.is_ascii_uppercase()
            && next.is_some_and(|n| n.is_ascii_uppercase())
            && after_next.is_some_and(|n| n.is_ascii_lowercase());
        let lower_to_upper = (c.is_ascii_lowercase() || c.is_ascii_digit())
            && next.is_some_and(|n| n.is_ascii_uppercase());
        if upper_run_boundary || lower_to_upper {
            separated.push('_');
        }
    }
    separated
        .split(|c: char| matches!(c, '.' | '_' | '-') || is_python_whitespace(c))
        .filter(|part| !part.is_empty())
        .map(str::to_lowercase)
        .collect()
}

fn is_test_directory(name: &str) -> bool {
    let lowered = name.to_lowercase();
    if TEST_WORDS.contains(&lowered.as_str()) || TEST_DIRECTORY_NAMES.contains(&lowered.as_str()) {
        return true;
    }
    TEST_DIRECTORY_KINDS.iter().any(|kind| {
        lowered
            .strip_prefix(kind)
            .is_some_and(|rest| rest == "test" || rest == "tests")
    })
}

/// Port of `match_test_path` for a project-relative path.
pub fn match_test_path(path: &Path) -> Option<Rule> {
    let parts = path_parts(path);
    let (name, directories) = parts.split_last()?;
    for directory in directories {
        let parts = words(directory);
        let last_word_is_test = parts
            .last()
            .is_some_and(|part| TEST_WORDS.contains(&part.as_str()));
        if is_test_directory(directory) || last_word_is_test {
            return Some(Rule::new(None, ExclusionKind::Directory, directory));
        }
    }
    let stem = Path::new(name)
        .file_stem()
        .map(|stem| stem.to_string_lossy().into_owned())
        .unwrap_or_default();
    let parts = words(&stem);
    if name.eq_ignore_ascii_case("conftest.py") {
        return Some(Rule::new(None, ExclusionKind::Filename, "conftest.py"));
    }
    for part in &parts {
        if TEST_WORDS.contains(&part.as_str()) || part == "e2e" {
            return Some(Rule::new(None, ExclusionKind::Filename, part));
        }
    }
    if name.to_lowercase().contains(".cy.") {
        return Some(Rule::new(None, ExclusionKind::Filename, ".cy."));
    }
    let suffix = Path::new(name)
        .extension()
        .map(|extension| format!(".{}", extension.to_string_lossy().to_lowercase()));
    if suffix.is_some_and(|suffix| JVM_SUFFIXES.contains(&suffix.as_str())) {
        let first_is_it = parts.first().is_some_and(|part| part == "it");
        let last_is_it = parts.last().is_some_and(|part| part == "it");
        let ends_with_it_case = parts.len() >= 2 && parts[parts.len() - 2..] == ["it", "case"];
        if first_is_it || last_is_it || ends_with_it_case {
            return Some(Rule::new(None, ExclusionKind::Filename, "IT / ITCase"));
        }
    }
    None
}

/// Port of `match_source_path`: directory components and generated
/// filename patterns, never incidental words in source filenames.
pub fn match_source_path(path: &Path) -> Option<Rule> {
    let parts = path_parts(path);
    let (name, directory_parts) = parts.split_last()?;
    let directories: Vec<String> = directory_parts
        .iter()
        .map(|part| part.to_lowercase())
        .collect();
    for (index, directory) in directories.iter().enumerate() {
        let directory = directory.as_str();
        let category = if OUTPUT_DIRECTORIES.contains(&directory)
            || directory == "generated"
            || directory == "__generated__"
        {
            Some(Category::Generated)
        } else if DEPENDENCY_DIRECTORIES.contains(&directory) {
            Some(Category::Dependency)
        } else if index == 0 && DOCUMENTATION_DIRECTORIES.contains(&directory) {
            Some(Category::Documentation)
        } else if AMBIGUOUS_OUTPUT_DIRECTORIES.contains(&directory) {
            let child = directories.get(index + 1).map_or("", String::as_str);
            let at_root = index == 0 && directory != "bin";
            if at_root || COMPILER_OUTPUT_CHILDREN.contains(&child) {
                Some(Category::Generated)
            } else {
                None
            }
        } else {
            None
        };
        if let Some(category) = category {
            return Some(Rule::new(
                Some(category),
                ExclusionKind::Directory,
                &directory_parts[index],
            ));
        }
    }
    if is_generated_filename(name) {
        return Some(Rule::new(
            Some(Category::Generated),
            ExclusionKind::Filename,
            name,
        ));
    }
    None
}

/// Port of the `GENERATED_FILENAME` pattern, matched case-insensitively.
fn is_generated_filename(name: &str) -> bool {
    let lowered = name.to_lowercase();
    if GENERATED_SUFFIXES
        .iter()
        .any(|suffix| lowered.ends_with(suffix))
    {
        return true;
    }
    let Some((stem, extension)) = lowered.rsplit_once('.') else {
        return false;
    };
    if extension.is_empty() {
        return false;
    }
    GENERATED_INFIXES
        .iter()
        .zip(GENERATED_INFIX_EXTENSIONS)
        .any(|(infix, required)| {
            let infix_marker = &infix[..infix.len() - 1];
            stem.ends_with(infix_marker) && required.is_none_or(|required| extension == required)
        })
}

fn generated_comment() -> &'static Regex {
    static PATTERN: OnceLock<Regex> = OnceLock::new();
    PATTERN.get_or_init(|| {
        Regex::new(GENERATED_COMMENT).expect("GENERATED_COMMENT is a valid pattern")
    })
}

/// Port of `match_generated_header`: explicit generated notices in leading
/// comments only, never in code or strings.
pub fn match_generated_header(text: &str) -> Option<Rule> {
    let text = text.trim_start_matches('\u{feff}');
    let head_end = text
        .char_indices()
        .nth(HEADER_CHARS)
        .map_or(text.len(), |(index, _)| index);
    let mut block = false;
    for line in pylines::split_lines_keepends(&text[..head_end])
        .into_iter()
        .take(HEADER_LINES)
    {
        let line = line.trim_matches(is_python_whitespace);
        if line.is_empty() || line.starts_with("#!") {
            continue;
        }
        let (comment, tail) = if block {
            let (comment, tail) = partition_block_end(line);
            block = tail.is_none();
            (comment, tail.unwrap_or(""))
        } else if let Some(rest) = line.strip_prefix("/*") {
            let (comment, tail) = partition_block_end(rest);
            block = tail.is_none();
            (comment, tail.unwrap_or(""))
        } else if let Some(rest) = line.strip_prefix("//") {
            (rest, "")
        } else if let Some(rest) = line.strip_prefix('#') {
            (rest, "")
        } else {
            break;
        };
        let comment = comment.trim_start_matches(['*', ' ', '!', '/', '\t']);
        if generated_comment().is_match(comment) {
            let matched: String = comment.chars().take(HEADER_MATCH_CHARS).collect();
            return Some(Rule::new(
                Some(Category::Generated),
                ExclusionKind::Header,
                matched,
            ));
        }
        if !tail.trim_matches(is_python_whitespace).is_empty() {
            break;
        }
    }
    None
}

/// `line.partition('*/')`: the text before the terminator and, when it
/// exists, the text after it.
fn partition_block_end(line: &str) -> (&str, Option<&str>) {
    match line.split_once("*/") {
        Some((comment, tail)) => (comment, Some(tail)),
        None => (line, None),
    }
}

/// Resolves `linguist-generated` and `linguist-vendored` through the
/// repository's attribute files, including nested rules and negations,
/// without the system attributes file.
fn git_attribute_rule(root: &Path, relative: &Path) -> Result<Option<Rule>> {
    let repository = Repository::open(root).map_err(Error::GitAttributes)?;
    let flags = AttrCheckFlags::FILE_THEN_INDEX | AttrCheckFlags::NO_SYSTEM;
    for (key, category) in GIT_ATTRIBUTES {
        let value = repository
            .get_attr(relative, key, flags)
            .map_err(Error::GitAttributes)?;
        if matches!(
            AttrValue::from_string(value),
            AttrValue::True | AttrValue::String("true")
        ) {
            return Ok(Some(Rule::new(
                Some(category),
                ExclusionKind::GitAttribute,
                key,
            )));
        }
    }
    Ok(None)
}

/// The scope rules of the qlty workspace that contains a file.
#[derive(Debug)]
pub struct QltyWorkspaceScope {
    root: PathBuf,
    relative: String,
    test_patterns: PatternSet,
    exclude_patterns: PatternSet,
}

#[derive(Debug, Default, Deserialize)]
struct WorkspacePatterns {
    #[serde(default)]
    test_patterns: Vec<String>,
    #[serde(default)]
    exclude_patterns: Vec<String>,
}

impl QltyWorkspaceScope {
    /// Finds the nearest ancestor holding `.qlty/qlty.toml` and reads its
    /// top-level patterns. Plugin sources are never fetched.
    pub fn for_path(path: &Path) -> Result<Option<Self>> {
        let cwd = env::current_dir()?;
        let absolute = absolute_lexical(path, &cwd);
        let Some(root) = absolute
            .ancestors()
            .skip(1)
            .find(|parent| parent.join(QLTY_CONFIG_PATH).is_file())
        else {
            return Ok(None);
        };
        let config_path = root.join(QLTY_CONFIG_PATH);
        let contents = fs::read_to_string(&config_path)?;
        let patterns: WorkspacePatterns =
            toml::from_str(&contents).map_err(|source| Error::WorkspaceConfig {
                path: config_path.clone(),
                source,
            })?;
        let relative = absolute
            .strip_prefix(root)
            .unwrap_or(&absolute)
            .to_string_lossy()
            .replace('\\', "/");
        Ok(Some(Self {
            root: root.to_path_buf(),
            relative,
            test_patterns: PatternSet::try_new(&patterns.test_patterns, &config_path)?,
            exclude_patterns: PatternSet::try_new(&patterns.exclude_patterns, &config_path)?,
        }))
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn test_exclusion(&self) -> Option<Exclusion> {
        let pattern = self.test_patterns.matched_pattern(&self.relative)?;
        Some(self.exclusion(
            ExclusionPolicy::QltyWorkspaceTestPatterns,
            Rule::new(None, ExclusionKind::Glob, pattern),
        ))
    }

    pub fn source_exclusion(&self) -> Option<Exclusion> {
        let pattern = self.exclude_patterns.matched_pattern(&self.relative)?;
        Some(self.exclusion(
            ExclusionPolicy::QltyWorkspaceExcludePatterns,
            Rule::new(Some(Category::Configured), ExclusionKind::Glob, pattern),
        ))
    }

    fn exclusion(&self, policy: ExclusionPolicy, rule: Rule) -> Exclusion {
        Exclusion {
            policy,
            matched_path: self.relative.clone(),
            path_scope: PathScope::QltyWorkspace,
            rule,
        }
    }
}

/// Glob patterns with qlty's `!` negation groups: the last group that
/// matches decides, and a negated group re-includes the file.
#[derive(Debug)]
struct PatternSet {
    groups: Vec<PatternGroup>,
}

#[derive(Debug)]
struct PatternGroup {
    patterns: Vec<String>,
    glob_set: GlobSet,
    negate: bool,
}

impl PatternSet {
    fn try_new(patterns: &[String], config_path: &Path) -> Result<Self> {
        let groups = ExcludeGroup::build_from_exclude_patterns(&patterns.to_vec())
            .into_iter()
            .map(|group| PatternGroup::try_new(group, config_path))
            .collect::<Result<Vec<_>>>()?;
        Ok(Self { groups })
    }

    /// The pattern that excludes `path`, if any.
    fn matched_pattern(&self, path: &str) -> Option<&str> {
        for group in self.groups.iter().rev() {
            let matches = group.glob_set.matches(path);
            let Some(&first) = matches.first() else {
                continue;
            };
            if group.negate {
                return None;
            }
            return group.patterns.get(first).map(String::as_str);
        }
        None
    }
}

impl PatternGroup {
    fn try_new(group: ExcludeGroup, config_path: &Path) -> Result<Self> {
        let mut builder = GlobSetBuilder::new();
        for pattern in &group.excludes {
            let glob = Glob::new(pattern).map_err(|source| Error::WorkspacePattern {
                path: config_path.to_path_buf(),
                pattern: pattern.clone(),
                source,
            })?;
            builder.add(glob);
        }
        let glob_set = builder.build().map_err(|source| Error::WorkspacePattern {
            path: config_path.to_path_buf(),
            pattern: group.excludes.join(", "),
            source,
        })?;
        Ok(Self {
            patterns: group.excludes,
            glob_set,
            negate: group.negate,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_rule(path: &str) -> Option<Rule> {
        match_test_path(Path::new(path))
    }

    #[test]
    fn splits_camel_case_words() {
        assert_eq!(words("HTTPTests"), ["http", "tests"]);
        assert_eq!(words("androidTest"), ["android", "test"]);
        assert_eq!(words("MyApp.UnitTests"), ["my", "app", "unit", "tests"]);
    }

    #[test]
    fn keeps_incidental_words_whole() {
        assert_eq!(words("Contest"), ["contest"]);
        assert_eq!(words("LatestVersion"), ["latest", "version"]);
    }

    #[test]
    fn directory_rule_reports_the_directory() {
        let rule = test_rule("src/androidTest/Example.kt").unwrap();
        assert_eq!(rule.kind(), ExclusionKind::Directory);
        assert_eq!(rule.matched(), "androidTest");
    }

    #[test]
    fn filename_rule_reports_the_word() {
        let rule = test_rule("src/ExampleTestCase.java").unwrap();
        assert_eq!(rule.kind(), ExclusionKind::Filename);
        assert_eq!(rule.matched(), "test");
    }

    #[test]
    fn conftest_is_a_test_file() {
        assert_eq!(
            test_rule("src/conftest.py").unwrap().matched(),
            "conftest.py"
        );
    }

    #[test]
    fn cypress_component_files_are_test_files() {
        assert_eq!(test_rule("src/component.cy.ts").unwrap().matched(), ".cy.");
    }

    #[test]
    fn jvm_integration_test_names_are_test_files() {
        assert_eq!(
            test_rule("src/ExampleITCase.java").unwrap().matched(),
            "IT / ITCase"
        );
        assert_eq!(
            test_rule("src/ITExample.java").unwrap().matched(),
            "IT / ITCase"
        );
    }

    #[test]
    fn it_names_outside_jvm_languages_are_source() {
        assert!(test_rule("src/it.rs").is_none());
    }

    #[test]
    fn generated_filenames_match_case_insensitively() {
        assert!(is_generated_filename("App.Bundle.JS"));
        assert!(is_generated_filename("query.generated.ts"));
        assert!(is_generated_filename("Widget.g.i.cs"));
        assert!(is_generated_filename("model.g.dart"));
    }

    #[test]
    fn generated_infix_requires_a_single_segment_extension() {
        assert!(!is_generated_filename("query.generated.d.ts"));
        assert!(!is_generated_filename("parser.gen."));
        assert!(!is_generated_filename("model.g.rs"));
    }

    #[test]
    fn ambiguous_output_directories_need_a_root_or_compiler_child() {
        assert!(match_source_path(Path::new("src/target/platform.rs")).is_none());
        assert!(match_source_path(Path::new("bin/server.py")).is_none());
        assert_eq!(
            match_source_path(Path::new("pkg/target/release/build/output.rs"))
                .unwrap()
                .matched(),
            "target"
        );
    }

    #[test]
    fn header_match_is_truncated_to_200_chars() {
        let text = format!("// @generated {}\n", "x".repeat(300));
        let rule = match_generated_header(&text).unwrap();
        assert_eq!(rule.matched().chars().count(), 200);
        assert_eq!(rule.kind(), ExclusionKind::Header);
    }

    #[test]
    fn header_scan_stops_at_code_after_a_block_comment() {
        assert!(match_generated_header("/* license */ const x = 1;\n// @generated\n").is_none());
    }

    #[test]
    fn header_scan_continues_through_multiline_block_comments() {
        assert!(
            match_generated_header("/*\n * Copyright\n */\n/* Code generated by protoc */\n")
                .is_some()
        );
    }

    #[test]
    fn header_scan_only_reads_the_first_100_lines() {
        let text = format!("{}// @generated\n", "// filler\n".repeat(100));
        assert!(match_generated_header(&text).is_none());
    }

    #[test]
    fn absolute_lexical_collapses_dot_segments() {
        let cwd = Path::new("/repo/src");
        assert_eq!(
            absolute_lexical(Path::new("../tests/./helper.rs"), cwd),
            Path::new("/repo/tests/helper.rs")
        );
        assert_eq!(absolute_lexical(Path::new("/../a"), cwd), Path::new("/a"));
    }

    #[test]
    fn relative_paths_resolve_against_the_working_directory() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path().join("tests").join("ExampleTests");
        fs::create_dir_all(project.join("src")).unwrap();
        fs::create_dir_all(project.join("tests")).unwrap();
        fs::write(project.join(".git"), "gitdir: /some/worktree\n").unwrap();
        let cwd = project.join("src");
        let scoped = ScopedPath::resolve_from(Path::new("../tests/helper.rs"), &cwd);
        assert_eq!(scoped.scope(), PathScope::GitRoot);
        assert_eq!(scoped.test_exclusion().unwrap().matched(), "tests");
        assert!(ScopedPath::resolve_from(Path::new("lib.rs"), &cwd)
            .test_exclusion()
            .is_none());
    }

    #[test]
    fn working_directory_scope_applies_without_markers() {
        let temp = tempfile::tempdir().unwrap();
        let scoped = ScopedPath::resolve_from(Path::new("src/lib.rs"), temp.path());
        assert_eq!(scoped.scope(), PathScope::WorkingDirectory);
        assert_eq!(scoped.relative(), Path::new("src/lib.rs"));
    }

    #[test]
    fn paths_outside_the_working_directory_use_absolute_scope() {
        let temp = tempfile::tempdir().unwrap();
        let file = temp.path().join("lib.rs");
        let scoped = ScopedPath::resolve_from(&file, Path::new("/nonexistent/cwd"));
        assert_eq!(scoped.scope(), PathScope::AbsolutePath);
        assert_eq!(scoped.relative(), file);
    }

    #[test]
    fn workspace_patterns_apply_negation_groups() {
        let temp = tempfile::tempdir().unwrap();
        let config = temp.path().join(QLTY_CONFIG_PATH);
        let set = PatternSet::try_new(
            &["vendor/**".to_string(), "!vendor/keep/**".to_string()],
            &config,
        )
        .unwrap();
        assert_eq!(set.matched_pattern("vendor/lib.js"), Some("vendor/**"));
        assert_eq!(set.matched_pattern("vendor/keep/lib.js"), None);
    }

    #[test]
    fn workspace_patterns_report_the_first_matching_pattern() {
        let temp = tempfile::tempdir().unwrap();
        let config = temp.path().join(QLTY_CONFIG_PATH);
        let set = PatternSet::try_new(
            &["**/*_test.go".to_string(), "**/test/**".to_string()],
            &config,
        )
        .unwrap();
        assert_eq!(
            set.matched_pattern("pkg/test/a_test.go"),
            Some("**/*_test.go")
        );
    }

    #[test]
    fn invalid_workspace_pattern_is_an_error() {
        let temp = tempfile::tempdir().unwrap();
        let config = temp.path().join(QLTY_CONFIG_PATH);
        let error = PatternSet::try_new(&["[".to_string()], &config).unwrap_err();
        assert!(matches!(error, Error::WorkspacePattern { .. }));
    }
}
