//! Chart values and drilldown rows against expectations generated by
//! slopdetect's `weekly_chart_data` functions on a synthetic two-snapshot
//! data set with changed, renamed, split, merged, added, and removed files.

mod common;

use common::assert_same_json;
use qlty_slop_one_trends::chart_data::{chart_periods, drilldown_periods};
use qlty_slop_one_trends::report::{ChangeKind, FilesExport, ReportData};
use serde_json::Value;

const DATA: &str = include_str!("fixtures/change/data.json");
const FILES: &str = include_str!("fixtures/change/files.json");
const CHART: &str = include_str!("fixtures/change/chart.json");
const DRILLDOWN: &str = include_str!("fixtures/change/drilldown.json");

fn fixture() -> (ReportData, FilesExport) {
    let data = ReportData::from_value(serde_json::from_str(DATA).unwrap()).unwrap();
    let files = FilesExport::from_value(serde_json::from_str(FILES).unwrap()).unwrap();
    (data, files)
}

#[test]
fn chart_periods_match_the_python_fixture() {
    let (data, files) = fixture();
    let chart = chart_periods(&data, &files).unwrap();
    let expected: Value = serde_json::from_str(CHART).unwrap();
    assert_same_json("chart", &expected, &serde_json::to_value(&chart).unwrap());
}

#[test]
fn baseline_period_has_no_values() {
    let (data, files) = fixture();
    let chart = chart_periods(&data, &files).unwrap();
    assert_eq!(chart[0].net, None);
    assert_eq!(chart[0].with_file_changes.net, None);
    assert_eq!(chart[0].additions, None);
}

#[test]
fn file_changes_fold_into_the_totals() {
    let (data, files) = fixture();
    let chart = chart_periods(&data, &files).unwrap();
    let period = &chart[1];
    let additions = period.additions.as_ref().unwrap();
    let removals = period.removals.as_ref().unwrap();
    assert_eq!(additions.files, 2);
    assert_eq!(additions.unscored_files, 1);
    assert_eq!(removals.files, 1);
    assert_eq!(removals.unscored_files, 1);
    let expected =
        period.positive.unwrap() + additions.positive.unwrap() + removals.positive.unwrap();
    assert!((period.with_file_changes.positive.unwrap() - expected).abs() < 1e-12);
}

#[test]
fn drilldown_periods_match_the_python_fixture() {
    let (data, files) = fixture();
    let drilldown = drilldown_periods(&data, &files).unwrap();
    let expected: Value = serde_json::from_str(DRILLDOWN).unwrap();
    assert_same_json(
        "drilldown",
        &expected,
        &serde_json::to_value(&drilldown).unwrap(),
    );
}

#[test]
fn drilldown_rows_are_ordered_by_absolute_contribution() {
    let (data, files) = fixture();
    let drilldown = drilldown_periods(&data, &files).unwrap();
    let kinds: Vec<ChangeKind> = drilldown[1].rows.iter().map(|row| row.kind).collect();
    assert_eq!(
        kinds,
        vec![
            ChangeKind::Split,
            ChangeKind::Changed,
            ChangeKind::Added,
            ChangeKind::Added,
            ChangeKind::Removed,
            ChangeKind::Renamed,
            ChangeKind::Merged,
        ]
    );
}

#[test]
fn drilldown_links_periods_by_commit() {
    let (data, files) = fixture();
    let drilldown = drilldown_periods(&data, &files).unwrap();
    assert_eq!(drilldown[0].before_commit, None);
    assert!(drilldown[0].rows.is_empty());
    assert_eq!(
        drilldown[1].before_commit.as_deref(),
        Some(drilldown[0].commit.as_str())
    );
}

#[test]
fn different_models_are_refused() {
    let (data, mut files) = fixture();
    files.model["sha256"] = Value::from("other");
    let error = chart_periods(&data, &files).unwrap_err();
    assert!(error.to_string().contains("different models"));
}

#[test]
fn different_commits_are_refused() {
    let (data, mut files) = fixture();
    files.periods[1].commit = "3333".to_owned();
    let error = chart_periods(&data, &files).unwrap_err();
    assert!(error.to_string().contains("different commits"));
}
