mod support;

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use chrono::DateTime;
use qlty_slop_one::jev;
use qlty_slop_one_trends::periods::Interval;
use qlty_slop_one_trends::run::{Manifest, RunDir, Snapshot, Version};
use qlty_slop_one_trends::snapshot::{freeze, FreezeOptions};
use qlty_slop_one_trends::Error;
use regex::Regex;
use serde_json::json;
use support::TestRepo;

const AS_OF: &str = "2025-07-15T12:00:00-04:00";
const SOURCE: &str = "export const value = 42;\n";
const PRISMA_HEADER: &str =
    "/* !!! This is code generated by Prisma. Do not edit directly. !!! */\nexport const value = 42;\n";

/// Three weekly commits: June 25, July 2, and July 9, 2025.
fn weekly_repo() -> (TestRepo, Vec<String>) {
    let repo = TestRepo::new();
    repo.write("src/a.ts", "export const a = 1;\n");
    let first = repo.commit("2025-06-25T12:00:00-04:00");
    repo.write("src/a.ts", "export const a = 2;\n");
    repo.write("src/b.ts", "export const b = 1;\n");
    let second = repo.commit("2025-07-02T12:00:00-04:00");
    repo.write("src/b.ts", "export const b = 2;\n");
    let third = repo.commit("2025-07-09T12:00:00-04:00");
    (repo, vec![first, second, third])
}

fn freeze_weekly(repo: &TestRepo) -> Manifest {
    let options = repo.options("2025-07-01", Interval::Week, AS_OF);
    freeze(&repo.run_dir("weekly"), &options).unwrap()
}

/// One commit in the week of July 7, 2025, holding `files`, frozen weekly.
fn freeze_files(repo: &TestRepo, files: &[(&str, &str)]) -> Manifest {
    for (path, contents) in files {
        repo.write(path, contents);
    }
    repo.commit("2025-07-02T12:00:00-04:00");
    repo.commit("2025-07-09T12:00:00-04:00");
    freeze_weekly(repo)
}

fn file_paths(snapshot: &Snapshot) -> Vec<&str> {
    snapshot
        .files
        .iter()
        .map(|entry| entry.path.as_str())
        .collect()
}

fn excluded_paths(snapshot: &Snapshot) -> Vec<&str> {
    snapshot
        .source_excluded
        .iter()
        .map(|entry| entry.path.as_str())
        .collect()
}

#[test]
fn freeze_selects_the_last_commit_before_each_week() {
    let (repo, commits) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    let selected: Vec<&str> = manifest
        .snapshots
        .iter()
        .map(|snapshot| snapshot.commit.as_str())
        .collect();
    assert_eq!(selected, [&commits[1], &commits[2], &commits[2]]);
}

#[test]
fn freeze_records_the_week_bounds() {
    let (repo, _) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    let starts: Vec<&str> = manifest
        .snapshots
        .iter()
        .map(|snapshot| snapshot.bounds.start())
        .collect();
    assert_eq!(starts, ["2025-06-30", "2025-07-07", "2025-07-14"]);
    assert_eq!(
        manifest.snapshots[0].bounds.end_exclusive(),
        "2025-07-07T00:00:00-04:00"
    );
}

#[test]
fn freeze_records_the_history_summary() {
    let (repo, commits) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    assert_eq!(manifest.first_commit, commits[0]);
    assert_eq!(manifest.first_commit_at, "2025-06-25T12:00:00-04:00");
    assert_eq!(manifest.main_commit, commits[2]);
    assert_eq!(manifest.first_parent_commits, 3);
    assert_eq!(manifest.nonmonotonic_commit_dates, 0);
    assert_eq!(manifest.git_ref, "HEAD");
}

#[test]
fn freeze_records_the_run_settings() {
    let (repo, _) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    assert_eq!(manifest.run_schema_version, 2);
    assert_eq!(manifest.interval, Interval::Week);
    assert_eq!(manifest.since, "2025-07-01");
    assert_eq!(manifest.created_at, AS_OF);
    assert_eq!(manifest.timezone, "America/New_York");
    assert_eq!(manifest.project, "demo");
    assert_eq!(manifest.repository, "https://github.com/owner/demo");
    assert_eq!(manifest.budget_usd, None);
    assert_eq!(
        manifest.source_exclusion_policy["id"],
        "authored-source-002"
    );
    assert_eq!(
        manifest.qlty.extractor_profile,
        manifest.model["extractor_profile"]
    );
}

#[test]
fn freeze_writes_the_manifest() {
    let (repo, _) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    let saved = repo.run_dir("weekly").load_manifest().unwrap();
    assert_eq!(saved, manifest);
}

#[test]
fn the_default_ref_follows_origin_head_when_configured() {
    let (repo, commits) = weekly_repo();
    let _ = &commits;
    repo.track_origin_main();
    repo.write("src/c.ts", "export const c = 1;\n");
    repo.commit("2025-07-10T12:00:00-04:00");
    let manifest = freeze_weekly(&repo);
    assert_eq!(manifest.git_ref, "refs/remotes/origin/main");
    assert_eq!(manifest.main_commit, commits[2]);
}

#[test]
fn an_explicit_ref_overrides_the_default() {
    let (repo, commits) = weekly_repo();
    let mut options = repo.options("2025-07-01", Interval::Week, AS_OF);
    options.git_ref = Some(commits[1].clone());
    let manifest = freeze(&repo.run_dir("weekly"), &options).unwrap();
    assert_eq!(manifest.main_commit, commits[1]);
    assert_eq!(manifest.first_parent_commits, 2);
}

#[test]
fn files_carry_blob_suffix_and_version() {
    let (repo, _) = weekly_repo();
    let manifest = freeze_weekly(&repo);
    let entry = &manifest.snapshots[0].files[0];
    assert_eq!(entry.path, "src/a.ts");
    assert_eq!(entry.suffix, ".ts");
    assert_eq!(entry.version, format!("{}.ts", entry.blob));
    assert!(manifest.versions.contains_key(&entry.version));
}

#[test]
fn unsupported_suffixes_are_counted() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[
            ("src/a.ts", SOURCE),
            ("package.json", "{}\n"),
            ("Makefile", "all:\n"),
            (".eslintrc", "{}\n"),
        ],
    );
    let expected: BTreeMap<String, usize> =
        [(".json".to_owned(), 1), ("[none]".to_owned(), 2)].into();
    assert_eq!(manifest.snapshots[0].other_extensions, expected);
    assert_eq!(file_paths(&manifest.snapshots[0]), ["src/a.ts"]);
}

/// Unix only because the fixture creates the modes through the filesystem;
/// the code under test reads them from Git trees and is not platform dependent.
#[cfg(unix)]
#[test]
fn non_regular_modes_are_counted() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", SOURCE);
    repo.write_executable("script/run.js", SOURCE);
    repo.symlink("src/link.ts", "a.ts");
    repo.commit("2025-07-02T12:00:00-04:00");
    repo.commit("2025-07-09T12:00:00-04:00");
    let manifest = freeze_weekly(&repo);
    let expected: BTreeMap<String, usize> = [("120000".to_owned(), 1)].into();
    assert_eq!(manifest.snapshots[0].excluded_modes, expected);
    assert_eq!(
        file_paths(&manifest.snapshots[0]),
        ["script/run.js", "src/a.ts"]
    );
}

#[test]
fn test_paths_are_skipped_with_their_rule() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[("src/a.ts", SOURCE), ("lib/module.test.ts", SOURCE)],
    );
    let skipped = &manifest.snapshots[0].skipped;
    assert_eq!(skipped.len(), 1);
    assert_eq!(skipped[0].path, "lib/module.test.ts");
    assert_eq!(
        skipped[0].reason,
        json!({"kind": "filename", "matched": "test"})
    );
    assert_eq!(file_paths(&manifest.snapshots[0]), ["src/a.ts"]);
}

#[test]
fn path_rules_exclude_before_reading_blobs() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[("src/a.ts", SOURCE), ("docs/prototype.tsx", SOURCE)],
    );
    let excluded = &manifest.snapshots[0].source_excluded;
    assert_eq!(excluded.len(), 1);
    assert_eq!(excluded[0].path, "docs/prototype.tsx");
    assert!(excluded[0].blob.is_some());
    assert_eq!(excluded[0].suffix, None);
    assert_eq!(excluded[0].version, None);
    assert_eq!(excluded[0].source_sha256, None);
    assert_eq!(
        excluded[0].exclusion,
        json!({
            "policy": "authored-source-002",
            "category": "documentation",
            "kind": "directory",
            "matched": "docs",
        })
    );
}

#[test]
fn generated_headers_exclude_versions_after_reading_blobs() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[
            ("src/a.ts", SOURCE),
            ("lib/prisma/client.ts", PRISMA_HEADER),
        ],
    );
    let excluded = &manifest.snapshots[0].source_excluded;
    assert_eq!(excluded.len(), 1);
    assert_eq!(excluded[0].path, "lib/prisma/client.ts");
    assert_eq!(excluded[0].suffix.as_deref(), Some(".ts"));
    assert!(excluded[0].source_sha256.is_some());
    assert_eq!(excluded[0].exclusion["kind"], "header");
    assert_eq!(excluded[0].exclusion["policy"], "authored-source-002");
    assert_eq!(file_paths(&manifest.snapshots[0]), ["src/a.ts"]);
    assert_eq!(manifest.versions.len(), 1);
}

#[test]
fn git_attributes_apply_at_each_frozen_commit() {
    let repo = TestRepo::new();
    repo.write("workers/create-backup.ts", SOURCE);
    repo.write("embedded/output.ts", SOURCE);
    repo.write("embedded/authored.ts", "export const authored = 1;\n");
    repo.write(".gitattributes", "embedded/** linguist-generated\n");
    repo.write(
        "embedded/.gitattributes",
        "authored.ts -linguist-generated\n",
    );
    repo.commit("2025-07-02T12:00:00-04:00");
    repo.commit("2025-07-09T12:00:00-04:00");
    repo.write(".gitattributes", "** linguist-generated\n");
    fs::create_dir_all(repo.path().join(".git/info")).unwrap();
    fs::write(
        repo.path().join(".git/info/attributes"),
        "workers/** linguist-generated\n",
    )
    .unwrap();
    let manifest = freeze_weekly(&repo);
    let snapshot = &manifest.snapshots[0];
    assert_eq!(
        file_paths(snapshot),
        ["embedded/authored.ts", "workers/create-backup.ts"]
    );
    assert_eq!(excluded_paths(snapshot), ["embedded/output.ts"]);
    assert_eq!(
        snapshot.source_excluded[0].exclusion,
        json!({
            "policy": "authored-source-002",
            "category": "generated",
            "kind": "git-attribute",
            "matched": "linguist-generated",
        })
    );
    assert_eq!(
        snapshot.source_excluded[0].version.as_deref(),
        Some(
            format!(
                "{}.ts",
                snapshot.source_excluded[0].blob.as_deref().unwrap()
            )
            .as_str()
        )
    );
}

#[test]
fn git_attribute_changes_only_affect_later_snapshots() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", SOURCE);
    repo.write("gen/out.ts", SOURCE);
    repo.commit("2025-07-02T12:00:00-04:00");
    repo.write(".gitattributes", "gen/** linguist-vendored\n");
    repo.commit("2025-07-09T12:00:00-04:00");
    let manifest = freeze_weekly(&repo);
    assert_eq!(
        file_paths(&manifest.snapshots[0]),
        ["gen/out.ts", "src/a.ts"]
    );
    assert_eq!(file_paths(&manifest.snapshots[1]), ["src/a.ts"]);
    assert_eq!(
        manifest.snapshots[1].source_excluded[0].exclusion["category"],
        "dependency"
    );
}

#[test]
fn the_attribute_reader_leaves_no_files_behind() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", SOURCE);
    repo.write(".gitattributes", "gen/** linguist-vendored\n");
    repo.commit("2025-07-02T12:00:00-04:00");
    repo.commit("2025-07-09T12:00:00-04:00");
    freeze_weekly(&repo);
    let entries: BTreeSet<String> = fs::read_dir(repo.run_dir("weekly").root())
        .unwrap()
        .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
        .collect();
    assert_eq!(
        entries,
        ["manifest.json", "prepared", "sources"]
            .into_iter()
            .map(str::to_owned)
            .collect()
    );
}

#[test]
fn workspace_patterns_replace_the_default_rules() {
    let repo = TestRepo::new();
    repo.write(
        ".qlty/qlty.toml",
        "config_version = \"0\"\ntest_patterns = [\"**/*_spec.ts\"]\nexclude_patterns = [\"legacy/**\"]\n",
    );
    let manifest = freeze_files(
        &repo,
        &[
            ("lib/module.test.ts", SOURCE),
            ("lib/thing_spec.ts", SOURCE),
            ("legacy/old.ts", SOURCE),
            ("lib/prisma/client.ts", PRISMA_HEADER),
        ],
    );
    let snapshot = &manifest.snapshots[0];
    assert_eq!(
        file_paths(snapshot),
        ["lib/module.test.ts", "lib/prisma/client.ts"]
    );
    assert_eq!(snapshot.skipped[0].path, "lib/thing_spec.ts");
    assert_eq!(
        snapshot.skipped[0].reason,
        json!({"kind": "glob", "matched": "**/*_spec.ts"})
    );
    assert_eq!(excluded_paths(snapshot), ["legacy/old.ts"]);
    assert_eq!(
        snapshot.source_excluded[0].exclusion,
        json!({
            "policy": "qlty-workspace-exclude-patterns",
            "category": "configured",
            "kind": "glob",
            "matched": "legacy/**",
        })
    );
    assert_eq!(
        manifest.source_exclusion_policy["id"],
        "qlty-workspace-exclude-patterns"
    );
    assert_eq!(
        manifest.source_exclusion_policy["git_attributes"],
        "Not applied; qlty workspace exclude_patterns replace the default source rules."
    );
    assert!(manifest
        .scope
        .contains("replacing the default test-path exclusions"));
}

#[test]
fn workspace_patterns_with_an_extender_are_checked_before_the_default_rules() {
    let repo = TestRepo::new();
    repo.write(
        ".qlty/qlty.toml",
        "config_version = \"0\"\ntest_patterns = [\"...\", \"**/*_spec.ts\"]\nexclude_patterns = [\"...\", \"legacy/**\"]\n",
    );
    repo.write(".gitattributes", "gen/** linguist-generated\n");
    let manifest = freeze_files(
        &repo,
        &[
            ("lib/module.test.ts", SOURCE),
            ("lib/thing_spec.ts", SOURCE),
            ("legacy/old.ts", SOURCE),
            ("docs/prototype.tsx", SOURCE),
            ("gen/output.ts", SOURCE),
            ("lib/prisma/client.ts", PRISMA_HEADER),
            ("src/a.ts", SOURCE),
        ],
    );
    let snapshot = &manifest.snapshots[0];
    assert_eq!(file_paths(snapshot), ["src/a.ts"]);
    assert_eq!(
        snapshot
            .skipped
            .iter()
            .map(|skipped| (skipped.path.as_str(), skipped.reason.clone()))
            .collect::<Vec<_>>(),
        [
            (
                "lib/module.test.ts",
                json!({"kind": "filename", "matched": "test"})
            ),
            (
                "lib/thing_spec.ts",
                json!({"kind": "glob", "matched": "**/*_spec.ts"})
            ),
        ]
    );
    assert_eq!(
        excluded_paths(snapshot),
        [
            "docs/prototype.tsx",
            "legacy/old.ts",
            "gen/output.ts",
            "lib/prisma/client.ts"
        ]
    );
    assert_eq!(
        snapshot
            .source_excluded
            .iter()
            .map(|excluded| (excluded.path.as_str(), excluded.exclusion["policy"].clone()))
            .collect::<Vec<_>>(),
        [
            ("docs/prototype.tsx", json!("authored-source-002")),
            ("legacy/old.ts", json!("qlty-workspace-exclude-patterns")),
            ("gen/output.ts", json!("authored-source-002")),
            ("lib/prisma/client.ts", json!("authored-source-002")),
        ]
    );
    assert_eq!(
        manifest.source_exclusion_policy["id"],
        "authored-source-002"
    );
    assert_eq!(
        manifest.source_exclusion_policy["git_attributes"],
        "Each frozen commit, without checkout/global/system overrides."
    );
    assert!(manifest
        .scope
        .contains("checked before the default test-path exclusions"));
}

#[test]
fn identical_content_shares_one_version_and_key_per_suffix() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[
            ("a.ts", SOURCE),
            ("b.ts", SOURCE),
            ("c.js", SOURCE),
            ("d.mjs", SOURCE),
        ],
    );
    assert_eq!(manifest.versions.len(), 3);
    assert_eq!(manifest.measurement_keys().len(), 3);
    assert_eq!(manifest.snapshots[0].files.len(), 4);
}

#[test]
fn prepared_text_is_written_by_measurement_key() {
    let repo = TestRepo::new();
    let manifest = freeze_files(&repo, &[("src/a.ts", SOURCE)]);
    let run = repo.run_dir("weekly");
    let (version, row) = manifest.versions.iter().next().unwrap();
    let key = jev::digest(&json!([".ts", SOURCE])).unwrap();
    assert_eq!(row.measurement_key.as_deref(), Some(key.as_str()));
    assert_eq!(
        row.source.as_deref(),
        Some(format!("sources/{version}").as_str())
    );
    assert_eq!(row.bytes, SOURCE.len());
    assert_eq!(row.prepared_bytes, Some(SOURCE.len()));
    assert_eq!(row.excerpts, Some(1));
    assert_eq!(
        fs::read_to_string(run.prepared_path(&key, ".ts")).unwrap(),
        SOURCE
    );
    assert_eq!(
        fs::read_to_string(run.source_path(version)).unwrap(),
        SOURCE
    );
    assert_eq!(row.source_scope.as_ref().unwrap()["policy"], "whole-file");
}

#[test]
fn source_sha256_hashes_the_raw_blob() {
    let repo = TestRepo::new();
    let manifest = freeze_files(&repo, &[("src/a.ts", SOURCE)]);
    let row = manifest.versions.values().next().unwrap();
    assert_eq!(row.source_sha256, sha256_hex(SOURCE.as_bytes()));
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::Digest as _;
    format!("{:x}", sha2::Sha256::digest(bytes))
}

#[test]
fn line_endings_are_normalized_before_keying() {
    let repo = TestRepo::new();
    let crlf = SOURCE.replace('\n', "\r\n");
    let manifest = freeze_files(&repo, &[("src/a.ts", &crlf)]);
    let row = manifest.versions.values().next().unwrap();
    let key = jev::digest(&json!([".ts", SOURCE])).unwrap();
    assert_eq!(row.bytes, crlf.len());
    assert_eq!(row.prepared_bytes, Some(SOURCE.len()));
    assert_eq!(row.measurement_key.as_deref(), Some(key.as_str()));
}

#[test]
fn rust_files_lose_their_inline_tests() {
    let repo = TestRepo::new();
    let text = "pub fn keep() {}\n#[cfg(test)]\nmod tests {\n    fn gone() {}\n}\n";
    let manifest = freeze_files(&repo, &[("src/lib.rs", text)]);
    let row = manifest.versions.values().next().unwrap();
    let key = jev::digest(&json!([".rs", "pub fn keep() {}\n"])).unwrap();
    assert_eq!(row.measurement_key.as_deref(), Some(key.as_str()));
    assert_eq!(
        row.source_scope.as_ref().unwrap()["policy"],
        "rust-inline-tests-001"
    );
    assert_eq!(row.source_scope.as_ref().unwrap()["excluded_lines"], 4);
}

#[test]
fn rust_test_only_files_are_skipped() {
    let repo = TestRepo::new();
    let manifest = freeze_files(
        &repo,
        &[(
            "src/inline.rs",
            "#[cfg(test)]\nmod tests {\n    fn x() {}\n}\n",
        )],
    );
    let row = manifest.versions.values().next().unwrap();
    assert_eq!(
        row.skipped.as_deref(),
        Some("No code remains after inline-test exclusion")
    );
    assert_eq!(row.measurement_key, None);
}

#[test]
fn empty_sources_record_an_error() {
    let repo = TestRepo::new();
    let manifest = freeze_files(&repo, &[("src/empty.ts", "")]);
    let row = manifest.versions.values().next().unwrap();
    assert!(row
        .error
        .as_deref()
        .unwrap()
        .starts_with("Source is empty or contains binary data: "));
    assert_eq!(row.measurement_key, None);
    assert_eq!(row.source_scope, None);
}

#[test]
fn too_few_snapshots_is_an_error() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", SOURCE);
    repo.commit("2025-07-09T12:00:00-04:00");
    let options = repo.options("2025-07-07", Interval::Week, "2025-07-10T12:00:00-04:00");
    let error = freeze(&repo.run_dir("weekly"), &options).unwrap_err();
    assert!(matches!(error, Error::TooFewSnapshots));
}

#[test]
fn refreezing_with_the_same_settings_returns_the_manifest() {
    let (repo, _) = weekly_repo();
    let first = freeze_weekly(&repo);
    repo.write("src/z.ts", SOURCE);
    repo.commit("2025-07-11T12:00:00-04:00");
    let second = freeze_weekly(&repo);
    assert_eq!(first, second);
}

#[test]
fn refreezing_with_a_different_start_is_an_error() {
    let (repo, _) = weekly_repo();
    freeze_weekly(&repo);
    let options = repo.options("2025-06-20", Interval::Week, AS_OF);
    let error = freeze(&repo.run_dir("weekly"), &options).unwrap_err();
    assert!(matches!(error, Error::Frozen(_)));
}

#[test]
fn refreezing_with_a_different_timezone_is_an_error() {
    let (repo, _) = weekly_repo();
    freeze_weekly(&repo);
    let mut options = repo.options("2025-07-01", Interval::Week, AS_OF);
    options.timezone = chrono_tz::UTC;
    let error = freeze(&repo.run_dir("weekly"), &options).unwrap_err();
    assert!(matches!(error, Error::Frozen(_)));
}

#[test]
fn refreezing_at_a_different_time_is_an_error() {
    let (repo, _) = weekly_repo();
    freeze_weekly(&repo);
    let options = repo.options("2025-07-01", Interval::Week, "2025-07-16T12:00:00-04:00");
    let error = freeze(&repo.run_dir("weekly"), &options).unwrap_err();
    assert!(matches!(error, Error::Frozen(_)));
}

#[test]
fn refreezing_without_an_as_of_keeps_the_frozen_time() {
    let (repo, _) = weekly_repo();
    let first = freeze_weekly(&repo);
    let mut options = repo.options("2025-07-01", Interval::Week, AS_OF);
    options.as_of = None;
    let second = freeze(&repo.run_dir("weekly"), &options).unwrap();
    assert_eq!(second.created_at, first.created_at);
}

#[test]
fn backdated_commits_are_counted_and_cannot_reverse_ancestry() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", "export const a = 1;\n");
    repo.commit("2025-07-01T12:00:00-04:00");
    repo.write("src/a.ts", "export const a = 2;\n");
    repo.commit("2025-07-08T12:00:00-04:00");
    repo.write("src/a.ts", "export const a = 3;\n");
    let backdated = repo.commit("2025-07-03T12:00:00-04:00");
    let manifest = freeze_weekly(&repo);
    assert_eq!(manifest.nonmonotonic_commit_dates, 1);
    assert_eq!(manifest.snapshots[1].commit, backdated);
    assert_eq!(
        manifest.snapshots[1].committed_at,
        "2025-07-03T12:00:00-04:00"
    );
}

#[test]
fn monthly_runs_include_the_preceding_month_end_baseline() {
    let repo = TestRepo::new();
    repo.write("logic.ts", SOURCE);
    repo.commit("2025-01-20T12:00:00-05:00");
    repo.write("logic.ts", "export const value = 43;\n");
    let month_end = repo.commit("2025-01-31T23:00:00-05:00");
    repo.write("logic.ts", SOURCE);
    repo.commit("2025-02-01T12:00:00-05:00");
    repo.write("logic.ts", "export const value = 44;\n");
    let tip = repo.commit("2025-02-10T12:00:00-05:00");
    let options = repo.options("2025-02-01", Interval::Month, "2025-02-15T12:00:00-05:00");
    let manifest = freeze(&repo.run_dir("monthly"), &options).unwrap();
    let starts: Vec<&str> = manifest
        .snapshots
        .iter()
        .map(|snapshot| snapshot.bounds.start())
        .collect();
    assert_eq!(starts, ["2025-01-01", "2025-02-01"]);
    assert_eq!(manifest.snapshots[0].commit, month_end);
    assert_eq!(manifest.snapshots[1].commit, tip);
    assert_eq!(manifest.interval, Interval::Month);
    assert!(manifest
        .snapshot_policy
        .starts_with("Last first-parent commit on the selected ref before the first day of each month 00:00 America/New_York; current month"));
}

#[test]
fn the_run_timezone_decides_the_week_of_a_sunday_night_commit() {
    let repo = TestRepo::new();
    repo.write("src/a.ts", "export const a = 1;\n");
    let origin = repo.commit("2025-06-20T12:00:00+00:00");
    repo.write("src/a.ts", "export const a = 2;\n");
    let late_sunday = repo.commit("2025-07-06T23:30:00-04:00");
    let mut options = repo.options("2025-06-30", Interval::Week, "2025-07-10T12:00:00+00:00");
    let new_york = freeze(&repo.run_dir("new-york"), &options).unwrap();
    options.timezone = chrono_tz::UTC;
    let utc = freeze(&repo.run_dir("utc"), &options).unwrap();
    assert_eq!(new_york.snapshots[0].commit, late_sunday);
    assert_eq!(utc.snapshots[0].commit, origin);
    assert_eq!(utc.timezone, "UTC");
    assert_eq!(
        utc.snapshots[0].bounds.end_exclusive(),
        "2025-07-07T00:00:00+00:00"
    );
}

#[test]
fn project_and_repository_can_be_overridden() {
    let (repo, _) = weekly_repo();
    let mut options = repo.options("2025-07-01", Interval::Week, AS_OF);
    options.project = Some("renamed".to_owned());
    options.repository_url = Some("git@example.com:group/renamed.git".to_owned());
    let manifest = freeze(&repo.run_dir("weekly"), &options).unwrap();
    assert_eq!(manifest.project, "renamed");
    assert_eq!(manifest.repository, "https://example.com/group/renamed");
}

#[test]
fn a_missing_origin_needs_a_repository_url() {
    let (repo, _) = weekly_repo();
    repo.repository().remote_delete("origin").unwrap();
    let options = repo.options("2025-07-01", Interval::Week, AS_OF);
    let error = freeze(&repo.run_dir("weekly"), &options).unwrap_err();
    assert!(matches!(error, Error::Configuration(_)));
}

#[test]
fn a_directory_without_a_repository_is_an_error() {
    let scratch = tempfile::tempdir().unwrap();
    let options = FreezeOptions {
        repo: scratch.path().to_path_buf(),
        since: "2025-07-01".parse().unwrap(),
        interval: Interval::Week,
        timezone: chrono_tz::UTC,
        git_ref: None,
        as_of: Some(DateTime::parse_from_rfc3339(AS_OF).unwrap()),
        project: None,
        repository_url: None,
        cache_directory: scratch.path().join("cache"),
    };
    let error = freeze(&RunDir::new(scratch.path().join("run")), &options).unwrap_err();
    assert!(matches!(error, Error::NotARepository(_)));
}

/// The Interface profile rules that the frozen slopdetect runs applied and
/// that decision 3 drops, as `fnmatchcase` patterns.
const INTERFACE_PROFILE_PATTERNS: [&str; 6] = [
    "public/workers/**",
    "public/faiss/**",
    "vector_db/public/faiss/**",
    "playwright/**",
    "jest.config.*",
    "jest.setup.*",
];

struct ParityFixture {
    frozen: Manifest,
    frozen_root: PathBuf,
    interface: PathBuf,
}

/// The slopdetect checkout and the Interface repository, when both are
/// available.
fn parity_fixture(run_name: &str) -> Option<ParityFixture> {
    let slopdetect = PathBuf::from(env::var_os("SLOPDETECT_DIR")?);
    let interface = PathBuf::from(env::var_os("INTERFACE_REPO")?);
    let frozen_root = slopdetect.join(".ai/local").join(run_name);
    let frozen = RunDir::new(&frozen_root).load_manifest().ok()?;
    Some(ParityFixture {
        frozen,
        frozen_root,
        interface,
    })
}

fn fnmatch(pattern: &str) -> Regex {
    let mut expression = String::from("^");
    for c in pattern.chars() {
        match c {
            '*' => expression.push_str(".*"),
            '?' => expression.push('.'),
            other => expression.push_str(&regex::escape(&other.to_string())),
        }
    }
    expression.push('$');
    Regex::new(&expression).unwrap()
}

fn profile_matched(path: &str) -> bool {
    INTERFACE_PROFILE_PATTERNS
        .iter()
        .any(|pattern| fnmatch(pattern).is_match(path))
}

fn normalize_error(error: Option<&str>, root: &Path) -> Option<String> {
    error.map(|text| text.replace(&root.to_string_lossy().into_owned(), "<run>"))
}

fn assert_interface_parity(run_name: &str, interval: Interval) {
    let Some(fixture) = parity_fixture(run_name) else {
        eprintln!("skipping {run_name}: set SLOPDETECT_DIR and INTERFACE_REPO");
        return;
    };
    let scratch = tempfile::tempdir().unwrap();
    let run = RunDir::new(scratch.path().join(run_name));
    let options = FreezeOptions {
        repo: fixture.interface.clone(),
        since: fixture.frozen.since.parse().unwrap(),
        interval,
        timezone: fixture.frozen.timezone.parse().unwrap(),
        git_ref: Some(fixture.frozen.git_ref.clone()),
        as_of: Some(DateTime::parse_from_rfc3339(&fixture.frozen.created_at).unwrap()),
        project: None,
        repository_url: None,
        cache_directory: scratch.path().join("cache"),
    };
    let mine = freeze(&run, &options).unwrap();
    let frozen = &fixture.frozen;

    assert_eq!(mine.main_commit, frozen.main_commit);
    assert_eq!(mine.first_commit, frozen.first_commit);
    assert_eq!(mine.first_commit_at, frozen.first_commit_at);
    assert_eq!(mine.first_parent_commits, frozen.first_parent_commits);
    assert_eq!(
        mine.nonmonotonic_commit_dates,
        frozen.nonmonotonic_commit_dates
    );
    assert_eq!(mine.project, frozen.project);
    assert_eq!(mine.repository, frozen.repository);
    assert_eq!(mine.snapshot_policy, frozen.snapshot_policy);
    assert_eq!(mine.snapshots.len(), frozen.snapshots.len());

    let mut differences: Vec<String> = Vec::new();
    for (ours, theirs) in mine.snapshots.iter().zip(&frozen.snapshots) {
        let start = ours.bounds.start();
        assert_eq!(ours.bounds, theirs.bounds);
        assert_eq!(ours.as_of, theirs.as_of);
        assert_eq!(ours.partial, theirs.partial);
        assert_eq!(ours.commit, theirs.commit);
        assert_eq!(ours.committed_at, theirs.committed_at);
        assert_eq!(ours.first_parent_index, theirs.first_parent_index);
        assert_eq!(ours.other_extensions, theirs.other_extensions);
        assert_eq!(ours.excluded_modes, theirs.excluded_modes);

        let our_files: BTreeMap<&str, &str> = ours
            .files
            .iter()
            .map(|entry| (entry.version.as_str(), entry.path.as_str()))
            .collect();
        let their_files: BTreeMap<&str, &str> = theirs
            .files
            .iter()
            .map(|entry| (entry.version.as_str(), entry.path.as_str()))
            .collect();
        differences.extend(
            their_files
                .iter()
                .filter(|(version, _)| !our_files.contains_key(*version))
                .map(|(version, path)| format!("{start}: file {path} ({version}) missing")),
        );
        differences.extend(
            our_files
                .iter()
                .filter(|(version, path)| {
                    !their_files.contains_key(*version) && !profile_matched(path)
                })
                .map(|(version, path)| format!("{start}: file {path} ({version}) unexplained")),
        );

        let our_skipped: BTreeSet<&str> = ours.skipped.iter().map(|s| s.path.as_str()).collect();
        let their_skipped: BTreeSet<&str> =
            theirs.skipped.iter().map(|s| s.path.as_str()).collect();
        differences.extend(
            our_skipped
                .symmetric_difference(&their_skipped)
                .map(|path| format!("{start}: skipped {path} differs")),
        );

        let our_excluded: HashSet<&str> = excluded_paths(ours).into_iter().collect();
        let their_excluded: HashSet<&str> = excluded_paths(theirs).into_iter().collect();
        differences.extend(
            our_excluded
                .difference(&their_excluded)
                .map(|path| format!("{start}: excluded {path} only in the qlty run")),
        );
        differences.extend(
            their_excluded
                .difference(&our_excluded)
                .filter(|path| !profile_matched(path))
                .map(|path| format!("{start}: excluded {path} only in the slopdetect run")),
        );
    }
    assert_eq!(differences, Vec::<String>::new());

    let mut compared = 0;
    for (version, theirs) in &frozen.versions {
        let Some(ours) = mine.versions.get(version) else {
            continue;
        };
        let ours = VersionSummary::new(ours, run.root());
        let theirs = VersionSummary::new(theirs, &fixture.frozen_root);
        if ours != theirs {
            differences.push(format!("{version}: {ours:?} != {theirs:?}"));
        }
        compared += 1;
    }
    assert_eq!(differences, Vec::<String>::new());
    assert_eq!(compared, frozen.versions.len());
    eprintln!(
        "{run_name}: {} snapshots, {} shared versions, {} versions only in the qlty run",
        mine.snapshots.len(),
        compared,
        mine.versions.len() - compared
    );
}

/// The prepared-source facts that must agree for a version in both runs.
#[derive(Debug, PartialEq)]
struct VersionSummary {
    suffix: String,
    bytes: usize,
    source_sha256: String,
    measurement_key: Option<String>,
    source_scope: Option<serde_json::Value>,
    skipped: Option<String>,
    prepared_bytes: Option<usize>,
    excerpts: Option<usize>,
    error: Option<String>,
}

impl VersionSummary {
    fn new(version: &Version, run_root: &Path) -> Self {
        Self {
            suffix: version.suffix.clone(),
            bytes: version.bytes,
            source_sha256: version.source_sha256.clone(),
            measurement_key: version.measurement_key.clone(),
            source_scope: version.source_scope.clone(),
            skipped: version.skipped.clone(),
            prepared_bytes: version.prepared_bytes,
            excerpts: version.excerpts,
            error: normalize_error(version.error.as_deref(), run_root),
        }
    }
}

#[test]
#[ignore = "needs SLOPDETECT_DIR and INTERFACE_REPO"]
fn interface_weekly_manifest_parity() {
    assert_interface_parity("interface-weekly-003", Interval::Week);
}

#[test]
#[ignore = "needs SLOPDETECT_DIR and INTERFACE_REPO"]
fn interface_monthly_manifest_parity() {
    assert_interface_parity("interface-monthly-001", Interval::Month);
}
