name: Plugin Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "qlty-plugins/**"
      - "qlty-config/**"
      - "qlty-check/src/tool/**"
      - ".github/workflows/plugins.yml"
  pull_request:
    paths:
      - "qlty-plugins/**"
      - "qlty-config/**"
      - "qlty-check/src/tool/**"
      - ".github/workflows/plugins.yml"

permissions:
  actions: write
  contents: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
    env:
      QLTY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          cache: "npm"
          cache-dependency-path: plugins/package-lock.json

      - name: Generate cache key
        run: echo "CACHE_MONTH=$(date +'%Y-%m')" >> $GITHUB_ENV

      - name: Cache qlty tools
        uses: actions/cache@v4
        with:
          path: ~/.qlty
          key: ${{ runner.os }}-qlty-${{ env.CACHE_MONTH }}-v1

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4
        if: contains(matrix.os, 'macos')

      - name: Setup Ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb
        with:
          ruby-version: 3.3.7
        if: contains(matrix.os, 'windows')

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a
        with:
          toolchain: stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: cargo build
        run: cargo build
        env:
          RUST_BACKTRACE: 1

      - name: Move qlty into PATH
        run: echo "${{ github.workspace }}/target/debug" >> $GITHUB_PATH

      - name: Check qlty version
        run: qlty --version

      - name: Run plugins tests
        working-directory: plugins
        run: |
          npm ci
          npm test
